version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: sistemaedu-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dbsistemaedu
      MYSQL_USER: sistemaedu_user
      MYSQL_PASSWORD: supersecret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: sistemaedu-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: sistemaedu.settings
      DB_NAME: dbsistemaedu
      DB_USER: sistemaedu_user
      DB_PASSWORD: supersecret
      DB_HOST: db
      DB_PORT: 3306

volumes:
  db_data:
