# Generated by Django 5.0.6 on 2024-05-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargarcontenido', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_resumen',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
