# Generated by Django 5.0.6 on 2024-06-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargarcontenido', '0003_video_video_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='resumen_ai',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='resumen',
            field=models.TextField(default='-'),
        ),
    ]
