# Generated by Django 5.0.6 on 2024-06-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargarcontenido', '0004_resumen_resumen_ai_alter_resumen_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='resumen_ai',
            field=models.TextField(default='-'),
        ),
    ]
