# Generated by Django 5.0.6 on 2024-06-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargarcontenido', '0005_documento_resumen_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='contenido_texto',
            field=models.TextField(default='-'),
        ),
    ]
