# Generated by Django 5.0.6 on 2024-06-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargarcontenido', '0006_documento_contenido_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='texto',
            field=models.TextField(default='-'),
        ),
    ]
