# Generated by Django 5.0.6 on 2024-06-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargarcontenido', '0008_video_reproducciones_videoreproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='descripcion',
            field=models.TextField(default='-'),
        ),
    ]
