# Generated by Django 5.0.6 on 2024-06-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargarcontenido', '0009_video_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='texto_resumen',
            field=models.TextField(default='-'),
        ),
    ]
