# Generated by Django 5.0.6 on 2024-07-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargarcontenido', '0010_video_texto_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genera_alumno',
            field=models.BooleanField(default=False),
        ),
    ]
